local _, ns = ...
local N = ns.N

-- Central visual constants. Structurally in the lineage of Cell (flat dark
-- surfaces, 1px black borders, accent-on-hover controls, titled panes) but
-- deliberately its own: a modern-blue accent instead of Cell's grey/class
-- default, and Nucleus' own proportions and typography.
local M = {}
N.Media = M

-- 1px white texture used for every bar and border fill.
M.flat = "Interface\\Buttons\\WHITE8X8"

-- Bar fill textures, selectable per group type (Appearance > Color). "flat"
-- is our own look (a solid tint, no shading); "gradient" and "modern" are
-- built-in Blizzard textures - not an asset we ship, just a path the client
-- already has - included because a flat tint reads noticeably paler than a
-- shaded bar even with the exact same class-color RGB behind it.
M.barTextures = {
    flat     = "Interface\\Buttons\\WHITE8X8",
    gradient = "Interface\\TargetingFrame\\UI-StatusBar",
    modern   = "Interface\\RaidFrame\\Raid-Bar-Hp-Fill",
    -- Our own default: a uniform 76.5% grey (NucleusBar3.tga, generated by
    -- tools/gen_textures.ps1). Grey rather than white so SetStatusBarColor's
    -- tint is multiplied down to a flat, matte, slightly deeper class colour -
    -- no gradient, no sheen.
    nucleus  = "Interface\\AddOns\\Nucleus\\Media\\Textures\\NucleusBar3.tga",
    -- Same family, no shading: a uniform white fill so the class/custom color
    -- shows completely flat across the whole bar, no vertical sheen at all.
    nucleus2 = "Interface\\AddOns\\Nucleus\\Media\\Textures\\NucleusBar2.tga",
    -- The previous default, kept as an option: a small grayscale vertical-sheen
    -- gradient (bright band near the top, easing down to a darker base),
    -- generated procedurally - see Media/Textures/NucleusBar.tga.
    nucleus3 = "Interface\\AddOns\\Nucleus\\Media\\Textures\\NucleusBar.tga",
}

-- Shield/absorb overlay textures (Appearance > Shield). "flat" is a plain
-- wash; "striped" is our own 45-degree hazard pattern - white RGB with the
-- alpha channel doing the striping, tiled horizontally, so
-- SetStatusBarColor's tint (and its alpha, multiplied against the stripe's
-- own alpha) lands the configured shield color with real texture instead of
-- a flat tint. Same underlying idea as Cell/Ellesmere's own (unrelated,
-- not copied) shield art.
M.shieldTextures = {
    flat    = "Interface\\Buttons\\WHITE8X8",
    striped = "Interface\\AddOns\\Nucleus\\Media\\Textures\\NucleusShield.tga",
}
-- Bundled font (SIL Open Font License, see Media/Fonts/TitilliumWeb-OFL.txt).
-- Shared across clients like every other Media/ asset - full Latin-1 coverage,
-- so German umlauts render fine.
M.font = "Interface\\AddOns\\Nucleus\\Media\\Fonts\\TitilliumWeb-Bold.ttf"

-- Shape textures for the options UI (generated by tools/gen_textures.ps1):
-- white RGB, alpha carries the shape, tinted with SetVertexColor. "round" and
-- "roundSm" are 9-sliced (SetTextureSliceMargins) so one small file scales to
-- any panel size; "circle" is a plain dot; "shadow" is a 9-sliced soft glow.
local TEX = "Interface\\AddOns\\Nucleus\\Media\\Textures\\"
M.tex = {
    round   = TEX .. "NucleusRound.tga",   -- 32px, radius 8, slice margin 9
    roundSm = TEX .. "NucleusRoundSm.tga", -- 16px, radius 4, slice margin 5
    circle  = TEX .. "NucleusCircle.tga",
    gear    = TEX .. "NucleusGear.tga",    -- 32px settings cog
    roles   = TEX .. "NucleusRoles.tga",   -- 128x32: tank / healer / damage tiles (square role icons)
    shadow  = TEX .. "NucleusShadow.tga",  -- 64px, slice margin 28, shape inset 14
    glowDash  = TEX .. "NucleusGlowDash.tga",  -- 32x4 tile: one dash, one gap (marching glow)
    empty     = TEX .. "NucleusEmpty.tga",     -- fully transparent (mask that hollows a ring)
    classSpec = TEX .. "NucleusClassSpec.tga", -- 512x512 sheet, 8x8 cells of 64px: class + spec icons (tools\gen_classspec_atlas.ps1)
    logo    = TEX .. "Logo.tga",           -- 128px addon logo (tools\gen_logo.ps1)
}

-- Cell index of each icon on the sheet above (row-major, 8 per row).
M.classSpecCells = {
    class = { DEMONHUNTER = 0, DRUID = 1, WARLOCK = 2, HUNTER = 3, WARRIOR = 4, MAGE = 5, MONK = 6, PALADIN = 7, PRIEST = 8, EVOKER = 9, SHAMAN = 10, ROGUE = 11, DEATHKNIGHT = 12 },
    spec = { [577] = 13, [581] = 14, [102] = 15, [103] = 16, [104] = 17, [105] = 18, [265] = 19, [266] = 20, [267] = 21, [253] = 22, [254] = 23, [255] = 24, [71] = 25, [72] = 26, [73] = 27, [62] = 28, [63] = 29, [64] = 30, [268] = 31, [269] = 32, [270] = 33, [65] = 34, [66] = 35, [70] = 36, [256] = 37, [257] = 38, [258] = 39, [1467] = 40, [1468] = 41, [1473] = 42, [262] = 43, [263] = 44, [264] = 45, [259] = 46, [260] = 47, [261] = 48, [250] = 49, [251] = 50, [252] = 51, [1480] = 52 },
}

M.color = {
    accent      = { 0.20, 0.55, 0.95, 1.00 }, -- modern blue highlight
    accentDim   = { 0.20, 0.55, 0.95, 0.18 },
    accentBright = { 0.42, 0.70, 1.00, 1.00 },
    accentHover = { 0.20, 0.55, 0.95, 0.55 }, -- Cell-style "accent-hover" fill
    navActive   = { 0.20, 0.55, 0.95, 0.85 }, -- held/active button fill
    navHover    = { 0.20, 0.55, 0.95, 0.45 },
    tabBand     = { 0.075, 0.080, 0.100, 0.97 }, -- top tab-strip ground (matches window)
    tabTint     = { 0.24, 0.56, 0.96, 0.16 },    -- active sub-tab wash
    itemHover   = { 1.00, 1.00, 1.00, 0.06 },    -- tab / sub-tab hover wash
    scrollTrack = { 1.00, 1.00, 1.00, 0.04 },
    scrollThumb = { 0.36, 0.38, 0.43, 1.00 },
    -- Options UI surfaces, darkest to lightest: window < segment < card < base.
    base        = { 0.140, 0.150, 0.175, 1.00 }, -- control fill (inputs, buttons)
    baseHover   = { 0.190, 0.203, 0.235, 1.00 },
    windowBg    = { 0.072, 0.078, 0.095, 0.97 }, -- options window ground
    navBg       = { 0.072, 0.078, 0.095, 0.97 },
    segment     = { 0.048, 0.052, 0.066, 1.00 }, -- recessed track (tab strip, mode switch)
    card        = { 0.104, 0.112, 0.134, 1.00 }, -- section surface
    line        = { 1.00, 1.00, 1.00, 0.075 },   -- hairlines / card dividers
    frameBg     = { 0.055, 0.058, 0.065, 0.95 },  -- unit frame ground
    border      = { 0.00, 0.00, 0.00, 1.00 },
    borderSoft  = { 1.00, 1.00, 1.00, 0.07 },
    borderInner = { 1.00, 1.00, 1.00, 0.05 },
    paneRule    = { 0.20, 0.55, 0.95, 0.55 },     -- accent underline under pane titles
    healthLoss  = { 0.065, 0.068, 0.075, 1.00 },  -- neutral, not blood-red - lets class color read
    text        = { 0.92, 0.92, 0.94, 1.00 },
    textDim     = { 0.58, 0.60, 0.65, 1.00 },
    aggro       = { 0.90, 0.15, 0.15, 1.00 },
    tank        = { 0.20, 0.55, 0.95, 1.00 },
}

-- Recolor every accent-derived entry from one base {r,g,b} (General >
-- Interface > Highlight color), keeping each entry's original alpha/
-- brightness relationship to the accent - only the hue changes. Mutates each
-- color table's r/g/b IN PLACE (same idea as Key Herald's GUI/Skin.lua
-- S.ApplyAccent) rather than replacing it with a new table, so anything that
-- kept a reference to e.g. M.color.accent sees the new values on its next
-- read - but a texture that already baked a color into itself via
-- SetColorTexture(unpack(...)) only repaints once something calls SetColorTexture
-- on it again. N.OnRecolor below is exactly that "repaint" registry.
function N.ApplyAccentColor(rgb)
    rgb = rgb or { 0.20, 0.55, 0.95 }
    local r, g, b = rgb[1], rgb[2], rgb[3]
    local mix = 0.35 -- how far accentBright lightens toward white
    local br, bg, bb = r + (1 - r) * mix, g + (1 - g) * mix, b + (1 - b) * mix

    local function set3(c, cr, cg, cb) c[1], c[2], c[3] = cr, cg, cb end
    set3(M.color.accent, r, g, b)
    set3(M.color.accentDim, r, g, b)
    set3(M.color.accentBright, br, bg, bb)
    set3(M.color.accentHover, r, g, b)
    set3(M.color.navActive, r, g, b)
    set3(M.color.navHover, r, g, b)
    set3(M.color.tabTint, r, g, b)
    set3(M.color.paneRule, r, g, b)
end

-- Widgets that bake the accent into a texture (SetColorTexture copies the
-- value, it isn't a live reference) register a small repaint closure here.
-- N.Recolor below mutates the palette then calls every one of them, so an
-- already-open options window updates live - same pattern as Key Herald's
-- GUI/Skin.lua S.recolorHooks / S.OnRecolor / S.Recolor.
local recolorHooks = {}
function N.OnRecolor(fn) recolorHooks[#recolorHooks + 1] = fn end

function N.Recolor(rgb)
    N.ApplyAccentColor(rgb)
    for _, fn in ipairs(recolorHooks) do pcall(fn) end
end

-- Call this instead of N.ApplyAccentColor whenever the UI might already be
-- built (i.e. from the options window itself) so the change is visible
-- without a /reload.

-- Resolve a class color to {r,g,b} - Blizzard's real, fixed class colors.
-- Deliberately NOT CUSTOM_CLASS_COLORS: that table reflects the player's own
-- "Custom Class Colors" override in the Blizzard options and would silently
-- drift from the actual game colors. C_ClassColor.GetClassColor is the
-- modern accessor for the same fixed table RAID_CLASS_COLORS holds.
-- Every step is pcall-guarded: a bad/secret/unexpected class token must never
-- abort the render() call that's about to also paint name/health text/power -
-- worst case this falls through to the neutral grey, it never throws.
function N.ClassRGB(class)
    if class == nil then return 0.6, 0.6, 0.6 end

    if C_ClassColor and C_ClassColor.GetClassColor then
        local ok, c = pcall(C_ClassColor.GetClassColor, class)
        if ok and c then
            local ok2, r, g, b = pcall(c.GetRGB, c)
            if ok2 and type(r) == "number" then return r, g, b end
        end
    end

    local ok3, c2 = pcall(function() return RAID_CLASS_COLORS[class] end)
    if ok3 and c2 then return c2.r, c2.g, c2.b end

    return 0.6, 0.6, 0.6
end
